/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
<<<<<<< HEAD

import java.sql.*;
import javax.swing.*;

import controller.UserController;
import models.User;

=======
import java.sql.*;
import javax.swing.*;

>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb
/**
 *
 * @author Dell
 */
public class newsignup extends javax.swing.JFrame {

    /**
<<<<<<< HEAD
     * Creates new form
=======
     * Creates new form 
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb
     */
    public newsignup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
<<<<<<< HEAD
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
=======
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfusername = new javax.swing.JTextField();
        tfdob = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfemail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tfpass = new javax.swing.JTextField();
        tfcpass = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnsignup = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tfsq = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setText("Bus Ticketing System");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 10, 420, 60);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SIGNUP");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(100, 10, 120, 32);

        jLabel5.setText("Already have an account? ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(63, 44, 138, 16);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Username");
        jPanel2.add(jLabel6);
<<<<<<< HEAD
        jLabel6.setBounds(10, 70, 66, 16);
=======
        jLabel6.setBounds(18, 72, 66, 16);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        tfusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfusernameActionPerformed(evt);
            }
        });
        jPanel2.add(tfusername);
<<<<<<< HEAD
        tfusername.setBounds(6, 94, 140, 30);
        jPanel2.add(tfdob);
        tfdob.setBounds(164, 94, 130, 30);
=======
        tfusername.setBounds(6, 94, 128, 22);
        jPanel2.add(tfdob);
        tfdob.setBounds(140, 94, 154, 22);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Date Of Birth");
        jPanel2.add(jLabel7);
<<<<<<< HEAD
        jLabel7.setBounds(170, 70, 75, 16);
=======
        jLabel7.setBounds(149, 72, 74, 16);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Email Address");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(12, 128, 96, 16);
        jPanel2.add(tfemail);
<<<<<<< HEAD
        tfemail.setBounds(6, 150, 131, 30);
=======
        tfemail.setBounds(6, 150, 131, 22);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Phone Number");
        jPanel2.add(jLabel9);
<<<<<<< HEAD
        jLabel9.setBounds(170, 130, 97, 16);
=======
        jLabel9.setBounds(143, 128, 97, 16);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        tfphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfphoneActionPerformed(evt);
            }
        });
        jPanel2.add(tfphone);
<<<<<<< HEAD
        tfphone.setBounds(170, 150, 130, 30);
=======
        tfphone.setBounds(143, 150, 151, 22);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Password");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(12, 184, 74, 16);

        tfpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpassActionPerformed(evt);
            }
        });
        jPanel2.add(tfpass);
<<<<<<< HEAD
        tfpass.setBounds(6, 206, 131, 30);
        jPanel2.add(tfcpass);
        tfcpass.setBounds(6, 258, 131, 30);
=======
        tfpass.setBounds(6, 206, 131, 22);
        jPanel2.add(tfcpass);
        tfcpass.setBounds(6, 258, 131, 22);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Confirm Password");
        jPanel2.add(jLabel11);
<<<<<<< HEAD
        jLabel11.setBounds(10, 240, 110, 16);
=======
        jLabel11.setBounds(6, 236, 110, 16);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        btnsignup.setBackground(new java.awt.Color(0, 51, 153));
        btnsignup.setForeground(new java.awt.Color(255, 255, 255));
        btnsignup.setText("Sign In");
        btnsignup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsignupActionPerformed(evt);
            }
        });
        jPanel2.add(btnsignup);
        btnsignup.setBounds(121, 370, 72, 31);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel12.setText("What's your pet name? (Security Question)");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(6, 298, 224, 14);
        jPanel2.add(tfsq);
<<<<<<< HEAD
        tfsq.setBounds(6, 318, 206, 30);
=======
        tfsq.setBounds(6, 318, 206, 22);
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        jPanel1.add(jPanel2);
        jPanel2.setBounds(880, 160, 310, 430);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/bus image.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -4, 1200, 600);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfusernameActionPerformed

    private void tfphoneActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfphoneActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tfphoneActionPerformed

    private void tfpassActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tfpassActionPerformed
        // TODO add your handling code here

    }// GEN-LAST:event_tfpassActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
        String username = tfusername.getText();
        String email = tfemail.getText();
        String pass = tfpass.getText();
        String Cpass = tfcpass.getText();
        String dob = tfdob.getText();
        String sq = tfsq.getText();
=======
    private void tfusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfusernameActionPerformed

    private void tfphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfphoneActionPerformed

    private void tfpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpassActionPerformed
        // TODO add your handling code here
 

    }//GEN-LAST:event_tfpassActionPerformed

    private void btnsignupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsignupActionPerformed
        // TODO add your handling code here:
               String username=tfusername.getText();
        String email=tfemail.getText();
        String pass=tfpass.getText();
        String Cpass=tfcpass.getText();
        String dob=tfdob.getText();
        String sq=tfsq.getText();
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb
        Connection conn;
        Statement pst;
        ResultSet rs;
        int value;

<<<<<<< HEAD
        if (evt.getSource() == btnsignup) {

            try {
                User u1 = new User(username, email, pass, Cpass, dob, sq);
                UserController uc = new UserController();
                int result = uc.insertDetails(u1);
                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Register Successfully");
                }

            } catch (Exception ex) {
                System.out.println("sql error" + ex);
                // Logger.getLogger(Signnnup.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }// GEN-LAST:event_btnsignupActionPerformed
=======
        if(evt.getSource()==btnsignup){

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/signupdb","root","Liban@1214");

                if(conn!=null){

                    System.out.println("connected to database successfully");
                    String sql="insert into user value('"+username+"','"+email+"','"+pass+"','"+Cpass+"','"+dob+"','"+sq+"')";
                pst=conn.createStatement();
                value=pst.executeUpdate(sql);

                if(value>0){
                    JOptionPane.showMessageDialog(rootPane, "User  registered Successfully");
                }
                else{
                    System.out.println("some error occured");

                }

                }else{System.out.println("failed to connet databse");}

                
            } catch (ClassNotFoundException ex) {
                ex.printStackTrace();
                System.out.println(ex);
                //Logger.getLogger(Signnnup.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                System.out.println("sql error"+ex);
                //Logger.getLogger(Signnnup.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnsignupActionPerformed
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
<<<<<<< HEAD
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
=======
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newsignup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
<<<<<<< HEAD
        // </editor-fold>
=======
        //</editor-fold>
>>>>>>> 837d3e218f57e9edbd1f812dabfab133ce834cdb

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newsignup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsignup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tfcpass;
    private javax.swing.JTextField tfdob;
    private javax.swing.JTextField tfemail;
    private javax.swing.JTextField tfpass;
    private javax.swing.JTextField tfphone;
    private javax.swing.JTextField tfsq;
    private javax.swing.JTextField tfusername;
    // End of variables declaration//GEN-END:variables
}
