/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
// package view;

import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import controller.TicketController;
import models.Ticket;
import controller.BusController;
import models.Bus;

/**
 *
 * @author gamer
 */
public class searchticket extends javax.swing.JFrame {

    /**
     * Creates new form searchticket
     */
    public searchticket() {
        initComponents();
        table();
        combo();
        combo1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        bookBTN = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();
        PriceFIlter = new javax.swing.JComboBox<>();
        refreshBtn = new javax.swing.JButton();
        goingTo = new javax.swing.JComboBox<>();
        fromTo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BrowseBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));

        jButton1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton1.setText("Filter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Home");

        jButton3.setText("Search Ticket");

        bookBTN.setText("Book Ticket");
        bookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBTNActionPerformed(evt);
            }
        });

        jButton5.setText("My Ticket");

        jButton6.setText("My Profile");

        jButton7.setText("Log Out");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Bus Ticketing System");

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Ticket no", "Bus  no", "Seat no", "Price", "Time"
                }));
        jScrollPane2.setViewportView(ticketTable);
        if (ticketTable.getColumnModel().getColumnCount() > 0) {
            ticketTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        }

        refreshBtn.setText("Refresh");
        refreshBtn.setToolTipText("");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");

        BrowseBtn.setText("Browse");
        BrowseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowseBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(328, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(205, 205, 205))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fromTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2))
                                                .addGap(35, 35, 35)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addGap(153, 153, 153)
                                                                                .addComponent(goingTo,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        118,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18))
                                                                        .addGroup(
                                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                                jPanel1Layout.createSequentialGroup()
                                                                                        .addComponent(jButton3)
                                                                                        .addGap(56, 56, 56)))
                                                                .addGroup(jPanel1Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(bookBTN)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(BrowseBtn)
                                                                                .addGap(85, 85, 85)
                                                                                .addComponent(refreshBtn)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        Short.MAX_VALUE)
                                                                                .addComponent(PriceFIlter,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jButton1))))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jButton2)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        Short.MAX_VALUE)
                                                                .addComponent(jButton5)
                                                                .addGap(55, 55, 55)
                                                                .addComponent(jButton6)
                                                                .addGap(61, 61, 61)
                                                                .addComponent(jButton7)))
                                                .addGap(33, 33, 33)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel1)
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton2)
                                        .addComponent(jButton3)
                                        .addComponent(bookBTN)
                                        .addComponent(jButton5)
                                        .addComponent(jButton6)
                                        .addComponent(jButton7))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(PriceFIlter, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(refreshBtn)
                                        .addComponent(goingTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fromTo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BrowseBtn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(43, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookBTNActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_bookBTNActionPerformed
        int i = ticketTable.getSelectedRow();
        TableModel model = ticketTable.getModel();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        Ticket t1 = new Ticket(id, 0, null, null, null, 0, null, null, null);
        TicketController tc = new TicketController();
        int result = tc.updateStatus(t1);
        if (result > 0) {
            dispose();
            new Bookticket().setVisible(true);
        }
    }// GEN-LAST:event_bookBTNActionPerformed

    private void BrowseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BrowseBtnActionPerformed
        try {
            String going = null;
            String from = null;
            Object selecteditem = goingTo.getSelectedItem();
            if (selecteditem != null) {
                going = selecteditem.toString();
            }
            Object selecteditem1 = fromTo.getSelectedItem();
            if (selecteditem1 != null) {
                from = selecteditem1.toString();
            }
            DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
            model.setRowCount(0);
            Ticket t1 = new Ticket(0, 0, null, null, null, 0, null, from, going);
            TicketController tc = new TicketController();
            ResultSet result = tc.browse(t1);
            while (result.next()) {
                String ticket = result.getString(1);
                String bus = result.getString(2);
                String seat_no = result.getString(4);
                String ticket_price = result.getString(6);
                String time = result.getString(7);

                // JOptionPane.showMessageDialog(null, ticket + " " + bus + " " + seat_no + " "
                // + ticket_price);
                Object[] row = { ticket, bus, seat_no, ticket_price, time };
                model.addRow(row);

            }
        } catch (Exception e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }// GEN-LAST:event_BrowseBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_refreshBtnActionPerformed
        table();
    }// GEN-LAST:event_refreshBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        try {
            String price = null;
            Object selecteditem = PriceFIlter.getSelectedItem();
            if (selecteditem != null) {
                price = selecteditem.toString();
            }
            DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
            model.setRowCount(0);
            Ticket t1 = new Ticket(0, 0, null, null, null, Integer.parseInt(price), null, null, null);
            TicketController tc = new TicketController();
            ResultSet result = tc.filter(t1);
            while (result.next()) {
                String ticket = result.getString(1);
                String bus = result.getString(2);
                String seat_no = result.getString(4);
                String ticket_price = result.getString(6);
                String time = result.getString(7);

                // JOptionPane.showMessageDialog(null, ticket + " " + bus + " " + seat_no + " "
                // + ticket_price);
                Object[] row = { ticket, bus, seat_no, ticket_price, time };
                model.addRow(row);

            }
        } catch (NumberFormatException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    public void combo() {
        try {
            Ticket t1 = new Ticket(0, 0, null, null, null, 0, null, null, null);
            TicketController tc = new TicketController();
            ResultSet result = tc.priceTicket(t1);

            while (result.next()) {
                String item = result.getString(1);
                boolean exist = false;
                for (int index = 0; index < PriceFIlter.getItemCount(); index++) {
                    if (item.equals(PriceFIlter.getItemAt(index))) {
                        exist = true;
                    }

                }
                if (exist != true) {
                    PriceFIlter.addItem(item);
                }
            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    public void table() {
        try {
            DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();
            model.setRowCount(0);
            Ticket t1 = new Ticket(0, 0, null, null, null, 0, null, null, null);
            TicketController tc = new TicketController();
            ResultSet result = tc.viewDetails(t1);
            while (result.next()) {
                String ticket = result.getString(1);
                String bus = result.getString(2);
                String seat_no = result.getString(4);
                String ticket_price = result.getString(6);
                String time = result.getString(7);

                // JOptionPane.showMessageDialog(null, ticket + " " + bus + " " + seat_no + " "
                // + ticket_price);
                Object[] row = { ticket, bus, seat_no, ticket_price, time };
                model.addRow(row);

            }
        } catch (Exception e) {
            // TODO: handle exception
        }

    }

    public void combo1() {
        try {
            Bus b1 = new Bus(0, 0, null, null, null, null);
            BusController bc = new BusController();
            ResultSet result = bc.viewBus(b1);
            while (result.next()) {
                String item = result.getString(1);
                String item2 = result.getString(2);
                boolean exist = false;
                for (int index = 0; index < fromTo.getItemCount(); index++) {
                    if (item.equals(fromTo.getItemAt(index))) {
                        exist = true;
                    }

                }
                if (exist != true) {
                    fromTo.addItem(item);
                }
                for (int index = 0; index < goingTo.getItemCount(); index++) {
                    if (item2.equals(goingTo.getItemAt(index))) {
                        exist = true;
                    }

                }
                if (exist != true) {
                    goingTo.addItem(item2);
                }
            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchticket.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchticket.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchticket.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchticket.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchticket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowseBtn;
    private javax.swing.JComboBox<String> PriceFIlter;
    private javax.swing.JButton bookBTN;
    private javax.swing.JComboBox<String> fromTo;
    private javax.swing.JComboBox<String> goingTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JTable ticketTable;
    // End of variables declaration//GEN-END:variables
}
