package view;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import controller.BusController;
import controller.TicketController;
import models.Bus;
import models.Ticket;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author budat
 */
public class viewbus extends javax.swing.JFrame {

    /**
     * Creates new form Bus
     */
    public viewbus() {
        initComponents();
        table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        myprofileBtn = new javax.swing.JToggleButton();
        addbusBtn = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        addticketBtn = new javax.swing.JToggleButton();
        ticketsBtn = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        homeBtn = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        deleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        busTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 153));

        jButton1.setText("Update");

        myprofileBtn.setText("My profile");
        myprofileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myprofileBtnActionPerformed(evt);
            }
        });

        addbusBtn.setText("Add Bus");
        addbusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbusBtnActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Log Out");

        addticketBtn.setText("Add Ticket");
        addticketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addticketBtnActionPerformed(evt);
            }
        });

        ticketsBtn.setText("Tickets");
        ticketsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketsBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bus Ticketing System");

        homeBtn.setText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        jToggleButton7.setText("View Bus");
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        busTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null },
                        { null, null, null, null, null }
                },
                new String[] {
                        "Bus no", "from city", "to city", "Num of seat", "License no"
                }));
        jScrollPane2.setViewportView(busTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addGap(45, 45, 45)
                                                .addComponent(deleteBtn)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jScrollPane2,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(homeBtn)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                        295, Short.MAX_VALUE)
                                                                .addComponent(addbusBtn)
                                                                .addGap(162, 162, 162)
                                                                .addComponent(jToggleButton7)
                                                                .addGap(170, 170, 170)
                                                                .addComponent(addticketBtn)
                                                                .addGap(145, 145, 145)
                                                                .addComponent(ticketsBtn)
                                                                .addGap(154, 154, 154)
                                                                .addComponent(myprofileBtn)
                                                                .addGap(133, 133, 133)
                                                                .addComponent(jToggleButton3)))
                                                .addGap(116, 116, 116)))));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(homeBtn)
                                        .addComponent(addbusBtn)
                                        .addComponent(myprofileBtn)
                                        .addComponent(ticketsBtn)
                                        .addComponent(jToggleButton7)
                                        .addComponent(addticketBtn)
                                        .addComponent(jToggleButton3))
                                .addGap(94, 94, 94)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 28,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(26, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void homeBtnActionPerformed(ActionEvent evt) {
        dispose();
        DashboardAdmin da = new DashboardAdmin();
        da.setVisible(true);
    }

    protected void ticketsBtnActionPerformed(ActionEvent evt) {
        dispose();
        viewTicketadmin vt = new viewTicketadmin();
        vt.setVisible(true);
    }

    protected void addticketBtnActionPerformed(ActionEvent evt) {
        dispose();
        newaddticket nt = new newaddticket();
        nt.setVisible(true);
    }

    protected void addbusBtnActionPerformed(ActionEvent evt) {
        dispose();
        MainFrame mf = new MainFrame();
        mf.setVisible(true);
    }

    protected void myprofileBtnActionPerformed(ActionEvent evt) {
        dispose();
        viewProfile vp = new viewProfile();
        vp.setVisible(true);
    }

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_deleteBtnActionPerformed
        TableModel model = busTable.getModel();
        int i = busTable.getSelectedRow();
        int id = Integer.parseInt(model.getValueAt(i, 0).toString());
        try {
            Ticket t1 = new Ticket(0, id, null, null, null, 0, null, null, null, null, null, null);
            TicketController tc = new TicketController();
            tc.deleteTicketBus(t1);
            Bus b1 = new Bus(id, 0, null, null, null, null);
            BusController bc = new BusController();
            bc.deleteBus(b1);
            table();
        } catch (Exception e) {
            // TODO: handle exception
        }
    }// GEN-LAST:event_deleteBtnActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton7ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jToggleButton7ActionPerformed

    public void table() {
        try {
            DefaultTableModel model = (DefaultTableModel) busTable.getModel();
            model.setRowCount(0);
            Bus b1 = new Bus(0, 0, null, null, null, null);
            BusController bc = new BusController();
            ResultSet result = bc.viewDetails(b1);
            while (result.next()) {
                String bus_no = result.getString(1);
                String seat_num = result.getString(2);
                String from_city = result.getString(3);
                String to_city = result.getString(4);
                String license_no = result.getString(6);
                System.out.println(bus_no + " " + " " + seat_num + " " + from_city + " " +
                        to_city + " " + license_no);
                Object[] row = { bus_no, from_city, to_city, seat_num, license_no };
                model.addRow(row);

            }
        } catch (HeadlessException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (Exception e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewbus.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewbus.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewbus.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewbus.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewbus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton addbusBtn;
    private javax.swing.JToggleButton addticketBtn;
    private javax.swing.JTable busTable;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JToggleButton homeBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton myprofileBtn;
    private javax.swing.JToggleButton ticketsBtn;
    // End of variables declaration//GEN-END:variables
}
